// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKvY4YJBjwRd4A28VPPlwbM59H1VLbtus',
    appId: '1:358344128917:web:00854c906ae2abb34f5e9c',
    messagingSenderId: '358344128917',
    projectId: 'todo-app-9023f',
    authDomain: 'todo-app-9023f.firebaseapp.com',
    storageBucket: 'todo-app-9023f.appspot.com',
    measurementId: 'G-S5VKGDLWGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzzWjdtSlA_vxz-zIps8DlXA5N_bF03v4',
    appId: '1:358344128917:android:d1a6db0619c5e6cd4f5e9c',
    messagingSenderId: '358344128917',
    projectId: 'todo-app-9023f',
    storageBucket: 'todo-app-9023f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8KINjqs_kQ9_hckroDVHmp2HLK8Dn_A',
    appId: '1:358344128917:ios:5445e9d85e0fd2be4f5e9c',
    messagingSenderId: '358344128917',
    projectId: 'todo-app-9023f',
    storageBucket: 'todo-app-9023f.appspot.com',
    iosClientId: '358344128917-iv7k130q039igfo8g9hakn53crh6qjnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE8KINjqs_kQ9_hckroDVHmp2HLK8Dn_A',
    appId: '1:358344128917:ios:17eea6d788f50fe84f5e9c',
    messagingSenderId: '358344128917',
    projectId: 'todo-app-9023f',
    storageBucket: 'todo-app-9023f.appspot.com',
    iosClientId: '358344128917-jdhr0lug6uoo8pod8146snt2us8f331h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
